package dev.benndorf.minitestframework;

import net.minecraft.world.entity.AreaEffectCloud;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ExperienceOrb;
import net.minecraft.world.entity.GlowSquid;
import net.minecraft.world.entity.LightningBolt;
import net.minecraft.world.entity.Marker;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.Bee;
import net.minecraft.world.entity.animal.Cat;
import net.minecraft.world.entity.animal.Chicken;
import net.minecraft.world.entity.animal.Cod;
import net.minecraft.world.entity.animal.Cow;
import net.minecraft.world.entity.animal.Dolphin;
import net.minecraft.world.entity.animal.Fox;
import net.minecraft.world.entity.animal.IronGolem;
import net.minecraft.world.entity.animal.MushroomCow;
import net.minecraft.world.entity.animal.Ocelot;
import net.minecraft.world.entity.animal.Panda;
import net.minecraft.world.entity.animal.Parrot;
import net.minecraft.world.entity.animal.Pig;
import net.minecraft.world.entity.animal.PolarBear;
import net.minecraft.world.entity.animal.Pufferfish;
import net.minecraft.world.entity.animal.Rabbit;
import net.minecraft.world.entity.animal.Salmon;
import net.minecraft.world.entity.animal.Sheep;
import net.minecraft.world.entity.animal.SnowGolem;
import net.minecraft.world.entity.animal.Squid;
import net.minecraft.world.entity.animal.TropicalFish;
import net.minecraft.world.entity.animal.Turtle;
import net.minecraft.world.entity.animal.Wolf;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.horse.Donkey;
import net.minecraft.world.entity.animal.horse.Horse;
import net.minecraft.world.entity.animal.horse.Llama;
import net.minecraft.world.entity.animal.horse.Mule;
import net.minecraft.world.entity.animal.horse.SkeletonHorse;
import net.minecraft.world.entity.animal.horse.TraderLlama;
import net.minecraft.world.entity.animal.horse.ZombieHorse;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.decoration.GlowItemFrame;
import net.minecraft.world.entity.decoration.ItemFrame;
import net.minecraft.world.entity.decoration.LeashFenceKnotEntity;
import net.minecraft.world.entity.decoration.Painting;
import net.minecraft.world.entity.item.FallingBlockEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.item.PrimedTnt;
import net.minecraft.world.entity.monster.Blaze;
import net.minecraft.world.entity.monster.CaveSpider;
import net.minecraft.world.entity.monster.Creeper;
import net.minecraft.world.entity.monster.Drowned;
import net.minecraft.world.entity.monster.ElderGuardian;
import net.minecraft.world.entity.monster.EnderMan;
import net.minecraft.world.entity.monster.Endermite;
import net.minecraft.world.entity.monster.Evoker;
import net.minecraft.world.entity.monster.Ghast;
import net.minecraft.world.entity.monster.Giant;
import net.minecraft.world.entity.monster.Guardian;
import net.minecraft.world.entity.monster.Husk;
import net.minecraft.world.entity.monster.Illusioner;
import net.minecraft.world.entity.monster.MagmaCube;
import net.minecraft.world.entity.monster.Phantom;
import net.minecraft.world.entity.monster.Pillager;
import net.minecraft.world.entity.monster.Ravager;
import net.minecraft.world.entity.monster.Shulker;
import net.minecraft.world.entity.monster.Silverfish;
import net.minecraft.world.entity.monster.Skeleton;
import net.minecraft.world.entity.monster.Slime;
import net.minecraft.world.entity.monster.Spider;
import net.minecraft.world.entity.monster.Stray;
import net.minecraft.world.entity.monster.Strider;
import net.minecraft.world.entity.monster.Vex;
import net.minecraft.world.entity.monster.Vindicator;
import net.minecraft.world.entity.monster.Witch;
import net.minecraft.world.entity.monster.WitherSkeleton;
import net.minecraft.world.entity.monster.Zoglin;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.entity.monster.ZombieVillager;
import net.minecraft.world.entity.monster.ZombifiedPiglin;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.entity.npc.WanderingTrader;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.entity.projectile.Arrow;
import net.minecraft.world.entity.projectile.DragonFireball;
import net.minecraft.world.entity.projectile.EvokerFangs;
import net.minecraft.world.entity.projectile.EyeOfEnder;
import net.minecraft.world.entity.projectile.FireworkRocketEntity;
import net.minecraft.world.entity.projectile.FishingHook;
import net.minecraft.world.entity.projectile.LargeFireball;
import net.minecraft.world.entity.projectile.LlamaSpit;
import net.minecraft.world.entity.projectile.ShulkerBullet;
import net.minecraft.world.entity.projectile.SmallFireball;
import net.minecraft.world.entity.projectile.Snowball;
import net.minecraft.world.entity.projectile.SpectralArrow;
import net.minecraft.world.entity.projectile.ThrownEgg;
import net.minecraft.world.entity.projectile.ThrownEnderpearl;
import net.minecraft.world.entity.projectile.ThrownExperienceBottle;
import net.minecraft.world.entity.projectile.ThrownPotion;
import net.minecraft.world.entity.projectile.ThrownTrident;
import net.minecraft.world.entity.projectile.WitherSkull;
import net.minecraft.world.entity.vehicle.Boat;
import net.minecraft.world.entity.vehicle.ChestBoat;
import net.minecraft.world.entity.vehicle.Minecart;
import net.minecraft.world.entity.vehicle.MinecartChest;
import net.minecraft.world.entity.vehicle.MinecartCommandBlock;
import net.minecraft.world.entity.vehicle.MinecartFurnace;
import net.minecraft.world.entity.vehicle.MinecartHopper;
import net.minecraft.world.entity.vehicle.MinecartSpawner;
import net.minecraft.world.entity.vehicle.MinecartTNT;

public class EntityTypeDelegate {

    public static final EntityType<Allay> ALLAY = EntityType.ALLAY;
    public static final EntityType<AreaEffectCloud> AREA_EFFECT_CLOUD = EntityType.AREA_EFFECT_CLOUD;
    public static final EntityType<ArmorStand> ARMOR_STAND = EntityType.ARMOR_STAND;
    public static final EntityType<Arrow> ARROW = EntityType.ARROW;
    public static final EntityType<Axolotl> AXOLOTL = EntityType.AXOLOTL;
    public static final EntityType<Bat> BAT = EntityType.BAT;
    public static final EntityType<Bee> BEE = EntityType.BEE;
    public static final EntityType<Blaze> BLAZE = EntityType.BLAZE;
    public static final EntityType<Boat> BOAT = EntityType.BOAT;
    public static final EntityType<Cat> CAT = EntityType.CAT;
    public static final EntityType<CaveSpider> CAVE_SPIDER = EntityType.CAVE_SPIDER;
    public static final EntityType<ChestBoat> CHEST_BOAT = EntityType.CHEST_BOAT;
    public static final EntityType<Chicken> CHICKEN = EntityType.CHICKEN;
    public static final EntityType<Cod> COD = EntityType.COD;
    public static final EntityType<Cow> COW = EntityType.COW;
    public static final EntityType<Creeper> CREEPER = EntityType.CREEPER;
    public static final EntityType<Dolphin> DOLPHIN = EntityType.DOLPHIN;
    public static final EntityType<Donkey> DONKEY = EntityType.DONKEY;
    public static final EntityType<DragonFireball> DRAGON_FIREBALL = EntityType.DRAGON_FIREBALL;
    public static final EntityType<Drowned> DROWNED = EntityType.DROWNED;
    public static final EntityType<ElderGuardian> ELDER_GUARDIAN = EntityType.ELDER_GUARDIAN;
    public static final EntityType<EndCrystal> END_CRYSTAL = EntityType.END_CRYSTAL;
    public static final EntityType<EnderDragon> ENDER_DRAGON = EntityType.ENDER_DRAGON;
    public static final EntityType<EnderMan> ENDERMAN = EntityType.ENDERMAN;
    public static final EntityType<Endermite> ENDERMITE = EntityType.ENDERMITE;
    public static final EntityType<Evoker> EVOKER = EntityType.EVOKER;
    public static final EntityType<EvokerFangs> EVOKER_FANGS = EntityType.EVOKER_FANGS;
    public static final EntityType<ExperienceOrb> EXPERIENCE_ORB = EntityType.EXPERIENCE_ORB;
    public static final EntityType<EyeOfEnder> EYE_OF_ENDER = EntityType.EYE_OF_ENDER;
    public static final EntityType<FallingBlockEntity> FALLING_BLOCK = EntityType.FALLING_BLOCK;
    public static final EntityType<FireworkRocketEntity> FIREWORK_ROCKET = EntityType.FIREWORK_ROCKET;
    public static final EntityType<Fox> FOX = EntityType.FOX;
    public static final EntityType<Frog> FROG = EntityType.FROG;
    public static final EntityType<Ghast> GHAST = EntityType.GHAST;
    public static final EntityType<Giant> GIANT = EntityType.GIANT;
    public static final EntityType<GlowItemFrame> GLOW_ITEM_FRAME = EntityType.GLOW_ITEM_FRAME;
    public static final EntityType<GlowSquid> GLOW_SQUID = EntityType.GLOW_SQUID;
    public static final EntityType<Goat> GOAT = EntityType.GOAT;
    public static final EntityType<Guardian> GUARDIAN = EntityType.GUARDIAN;
    public static final EntityType<Hoglin> HOGLIN = EntityType.HOGLIN;
    public static final EntityType<Horse> HORSE = EntityType.HORSE;
    public static final EntityType<Husk> HUSK = EntityType.HUSK;
    public static final EntityType<Illusioner> ILLUSIONER = EntityType.ILLUSIONER;
    public static final EntityType<IronGolem> IRON_GOLEM = EntityType.IRON_GOLEM;
    public static final EntityType<ItemEntity> ITEM = EntityType.ITEM;
    public static final EntityType<ItemFrame> ITEM_FRAME = EntityType.ITEM_FRAME;
    public static final EntityType<LargeFireball> FIREBALL = EntityType.FIREBALL;
    public static final EntityType<LeashFenceKnotEntity> LEASH_KNOT = EntityType.LEASH_KNOT;
    public static final EntityType<LightningBolt> LIGHTNING_BOLT = EntityType.LIGHTNING_BOLT;
    public static final EntityType<Llama> LLAMA = EntityType.LLAMA;
    public static final EntityType<LlamaSpit> LLAMA_SPIT = EntityType.LLAMA_SPIT;
    public static final EntityType<MagmaCube> MAGMA_CUBE = EntityType.MAGMA_CUBE;
    public static final EntityType<Marker> MARKER = EntityType.MARKER;
    public static final EntityType<Minecart> MINECART = EntityType.MINECART;
    public static final EntityType<MinecartChest> CHEST_MINECART = EntityType.CHEST_MINECART;
    public static final EntityType<MinecartCommandBlock> COMMAND_BLOCK_MINECART = EntityType.COMMAND_BLOCK_MINECART;
    public static final EntityType<MinecartFurnace> FURNACE_MINECART = EntityType.FURNACE_MINECART;
    public static final EntityType<MinecartHopper> HOPPER_MINECART = EntityType.HOPPER_MINECART;
    public static final EntityType<MinecartSpawner> SPAWNER_MINECART = EntityType.SPAWNER_MINECART;
    public static final EntityType<MinecartTNT> TNT_MINECART = EntityType.TNT_MINECART;
    public static final EntityType<Mule> MULE = EntityType.MULE;
    public static final EntityType<MushroomCow> MOOSHROOM = EntityType.MOOSHROOM;
    public static final EntityType<Ocelot> OCELOT = EntityType.OCELOT;
    public static final EntityType<Painting> PAINTING = EntityType.PAINTING;
    public static final EntityType<Panda> PANDA = EntityType.PANDA;
    public static final EntityType<Parrot> PARROT = EntityType.PARROT;
    public static final EntityType<Phantom> PHANTOM = EntityType.PHANTOM;
    public static final EntityType<Pig> PIG = EntityType.PIG;
    public static final EntityType<Piglin> PIGLIN = EntityType.PIGLIN;
    public static final EntityType<PiglinBrute> PIGLIN_BRUTE = EntityType.PIGLIN_BRUTE;
    public static final EntityType<Pillager> PILLAGER = EntityType.PILLAGER;
    public static final EntityType<PolarBear> POLAR_BEAR = EntityType.POLAR_BEAR;
    public static final EntityType<PrimedTnt> TNT = EntityType.TNT;
    public static final EntityType<Pufferfish> PUFFERFISH = EntityType.PUFFERFISH;
    public static final EntityType<Rabbit> RABBIT = EntityType.RABBIT;
    public static final EntityType<Ravager> RAVAGER = EntityType.RAVAGER;
    public static final EntityType<Salmon> SALMON = EntityType.SALMON;
    public static final EntityType<Sheep> SHEEP = EntityType.SHEEP;
    public static final EntityType<Shulker> SHULKER = EntityType.SHULKER;
    public static final EntityType<ShulkerBullet> SHULKER_BULLET = EntityType.SHULKER_BULLET;
    public static final EntityType<Silverfish> SILVERFISH = EntityType.SILVERFISH;
    public static final EntityType<Skeleton> SKELETON = EntityType.SKELETON;
    public static final EntityType<SkeletonHorse> SKELETON_HORSE = EntityType.SKELETON_HORSE;
    public static final EntityType<Slime> SLIME = EntityType.SLIME;
    public static final EntityType<SmallFireball> SMALL_FIREBALL = EntityType.SMALL_FIREBALL;
    public static final EntityType<SnowGolem> SNOW_GOLEM = EntityType.SNOW_GOLEM;
    public static final EntityType<Snowball> SNOWBALL = EntityType.SNOWBALL;
    public static final EntityType<SpectralArrow> SPECTRAL_ARROW = EntityType.SPECTRAL_ARROW;
    public static final EntityType<Spider> SPIDER = EntityType.SPIDER;
    public static final EntityType<Squid> SQUID = EntityType.SQUID;
    public static final EntityType<Stray> STRAY = EntityType.STRAY;
    public static final EntityType<Strider> STRIDER = EntityType.STRIDER;
    public static final EntityType<ThrownEgg> EGG = EntityType.EGG;
    public static final EntityType<ThrownEnderpearl> ENDER_PEARL = EntityType.ENDER_PEARL;
    public static final EntityType<ThrownExperienceBottle> EXPERIENCE_BOTTLE = EntityType.EXPERIENCE_BOTTLE;
    public static final EntityType<ThrownPotion> POTION = EntityType.POTION;
    public static final EntityType<Tadpole> TADPOLE = EntityType.TADPOLE;
    public static final EntityType<ThrownTrident> TRIDENT = EntityType.TRIDENT;
    public static final EntityType<TraderLlama> TRADER_LLAMA = EntityType.TRADER_LLAMA;
    public static final EntityType<TropicalFish> TROPICAL_FISH = EntityType.TROPICAL_FISH;
    public static final EntityType<Turtle> TURTLE = EntityType.TURTLE;
    public static final EntityType<Vex> VEX = EntityType.VEX;
    public static final EntityType<Villager> VILLAGER = EntityType.VILLAGER;
    public static final EntityType<Vindicator> VINDICATOR = EntityType.VINDICATOR;
    public static final EntityType<WanderingTrader> WANDERING_TRADER = EntityType.WANDERING_TRADER;
    public static final EntityType<Witch> WITCH = EntityType.WITCH;
    public static final EntityType<WitherBoss> WITHER = EntityType.WITHER;
    public static final EntityType<WitherSkeleton> WITHER_SKELETON = EntityType.WITHER_SKELETON;
    public static final EntityType<WitherSkull> WITHER_SKULL = EntityType.WITHER_SKULL;
    public static final EntityType<Wolf> WOLF = EntityType.WOLF;
    public static final EntityType<Zoglin> ZOGLIN = EntityType.ZOGLIN;
    public static final EntityType<Zombie> ZOMBIE = EntityType.ZOMBIE;
    public static final EntityType<ZombieHorse> ZOMBIE_HORSE = EntityType.ZOMBIE_HORSE;
    public static final EntityType<ZombieVillager> ZOMBIE_VILLAGER = EntityType.ZOMBIE_VILLAGER;
    public static final EntityType<ZombifiedPiglin> ZOMBIFIED_PIGLIN = EntityType.ZOMBIFIED_PIGLIN;
    public static final EntityType<Player> PLAYER = EntityType.PLAYER;
    public static final EntityType<FishingHook> FISHING_BOBBER = EntityType.FISHING_BOBBER;
}
